[package]
name = "synth_data"
version = "0.1.0"
edition = "2021"

[lib]
name = "synth_data"
path = "src/lib.rs"

[dependencies]
anyhow = "1.0.71"
blake2 = "0.10.6"
datafusion = "27.0.0"
rand = "0.8.5"
rand_chacha = "0.3.1"
tokio = "1.29.1"
