[package]
name = 'rhic'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rhic'

[dependencies]
extendr-api = '*'
rust_hic = { git = "https://github.com/jrs0/hic_arc_hbr" }
