# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rhic_wrappers", use_symbols = TRUE, package_name = "rhic")

#' @docType package
#' @usage NULL
#' @useDynLib rhic, .registration = TRUE
NULL

#' Test interface to Rust library
#' @export
hello_world <- function() invisible(.Call(wrap__hello_world))


# nolint end
