# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rhic_wrappers", use_symbols = TRUE, package_name = "rhic")

#' @docType package
#' @usage NULL
#' @useDynLib rhic, .registration = TRUE
NULL

#' Get the clinical codes in a particular code group defined
#' in a codes file.
#'
#' The result is a named list (intended as a dataframe) with the
#' columns:
#' * name: the name of the code in the group (e.g. A01.0)
#' * docs: the description of the code 
#' 
#' TODO: figure out a good way to hand errors.
#' 
#' @export
rust_get_codes_in_group <- function(codes_file_path, group) .Call(wrap__rust_get_codes_in_group, codes_file_path, group)


# nolint end
